apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-nginx
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 'nginx/nginx-ingress:1.7.1'
        ports:
        - containerPort: 80
